[package]
name = "kb_mouse"
version = "0.1.0"
edition = "2021"
description = "Kb Mouse (keyboard mouse), if mouse drivers aren't working you can use the arrow keys."
license = "MIT"
publish = false

[dependencies]
novuskinc = { git = "https://github.com/new-kernel/novuskinc", features = ["v3"] }
pc_keyboard = { path = "../../keyboard/pc_keyboard/" }
x86_64 = "0.14.6"
