[package]
name = "sifive"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
device = { path = "../../device/" }
hifive1 = "0.10.0"
novuskinc = { git = "https://github.com/new-kernel/novuskinc" }

[features]
default = []
hifive = ["hifive1/board-hifive1"]
lofive = ["hifive1/board-lofive"]
