[package]
name = "stellarisd"
version = "0.1.0"
edition = "2021"
description = "Board support for Stellaris boards"
license = "MIT"
publish = false

[dependencies]
cortex-m = "0.7.3"
cortex-m-semihosting = "0.3.7"
device = { path = "../../../device/" }
libbmu = { path = "../../../../lib/libbmu/" }
novuskinc = { git = "https://github.com/new-kernel/novuskinc", features = ["v3"] }
tm4c123x-hal = "0.10.2"

[features]
default = []
stellaris_6965 = []
