[package]
name = "ex1"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2021"
license = "MIT"
publish = false

[dependencies]
novuskinc = { path = "../../../include/novuskinc/", features = ["v3"] }
printk = { path = "../../printk/" }
