[package]
name = "rpi2kernel"
version = "0.1.0"
edition = "2021"
description = "RPi 2 specific kernel"
license = "MIT"
publish = false

[dependencies]
armfb = { path = "../../gpu/armfb/" }
console = { path = "../../../kernel/console/" }
fb = { path = "../../fb/" }
kinfo = { path = "../../../kernel/kinfo/" }
konfig = { path = "../../../kernel/konfig/" }
novuskinc = { path = "../../../include/novuskinc/", features = ["v3"] }
printk = { path = "../../../kernel/printk/" }
rpi = { path = "../", features = ["rpi2"] }
