[package]
name = "ethernet"
version = "0.1.0"
edition = "2021"
description = "For writing ethernet drivers"
license = "MIT"
publish = false

[dependencies]
novuskinc = { path = "../../../include/novuskinc/", features = ["v3"] }
