[package]
name = "stmd"
version = "0.1.0"
edition = "2021"
description = "Support for STM32 boards"
license = "MIT"
publish = false

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.1"
ethernet = { path = "../../../../drivers/net/ethernet/" }
kinfo = { path = "../../../../kernel/kinfo/" }
novuskinc = { git = "https://github.com/new-kernel/novuskinc"" }
stm_eth = { path = "../../../../net/ethernet/stm_eth/" }
stm32f4xx-hal = { version = "0.10.0", features = ["rt"] }

[features]
stm32f4xx = []
stm32f407 = ["stm32f4xx", "stm32f4xx-hal/stm32f407", "stm_eth/stm32f407"]
qemu = []
