[package]
name = "aarch64"
version = "0.1.0"
edition = "2021"
description = "Aarch64/arm64 kernel support"
license = "MIT"
publish = false

[dependencies]
armfb = { path = "../../drivers/gpu/armfb/" }
dif = "0.1.1"
init = { path = "../../init/" }
kinfo = { path = "../../kernel/kinfo/" }
nmallocator = { path = "../../mm/nmallocator/", features = ["wee_allocator"] }
novusk_syscalls = "0.2.1"
novuskinc = { path = "../../include/novuskinc/", features = ["v3"] }
setup = { path = "../../kernel/setup/" }
tock-registers = "0.7.0"
r0 = "1.0.0"
rpi = { path = "../../drivers/rpi/" }

[build-dependencies]
difi = "0.1.0"

[features]
rpi3 = ["rpi/rpi3"]
qemu_virt = []
